http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "domain.local"
            sans:
              - "*.domain.local"
    router0:
      entryPoints:
      - web
      service: apiserver
      rule: Path('/api')
    services:
      apiserver:
        loadBalancer:
          servers:
          - url: http://localhost:3000


tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
